services:
  kelly-trading:
    build: .
    container_name: kelly-trading-bot
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s